/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_yuzhakov_histology_Tetgen */

#ifndef _Included_org_yuzhakov_histology_Tetgen
#define _Included_org_yuzhakov_histology_Tetgen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_yuzhakov_histology_Tetgen
 * Method:    tetrahedralize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_yuzhakov_histology_Tetgen_tetrahedralize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
